lol

diff --git a/hell-installer b/hell-installer
--- a/hell-installer
+++ b/hell-installer
@@ -125,7 +125,7 @@ function __HELLSCRIPTS_INJECT_FUNS {
         function __HELLSCRIPTS_LOGGER {
             if [[ "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]" ]]
             then
-                2>&1 echo "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS
+                2>&1 echo -e "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS
             fi
         }
 
@@ -134,7 +134,7 @@ function __HELLSCRIPTS_INJECT_FUNS {
         function __HELLSCRIPTS_ERROR_LOGGER {
             if [[ $__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING] ]]
             then
-                >&2 echo "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS
+                >&2 echo -e "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS
             fi
         }
     }
