qsdsq

diff --git a/hell-installer b/hell-installer
--- a/hell-installer
+++ b/hell-installer
@@ -224,35 +224,33 @@ function __HELLSCRIPTS_INJECT_FUNS {
     }
 
     __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_INJECT_LOGGER..."
-    function __HELLSCRIPTS_INJECT_LOGGER {
-        type __HELLSCRIPTS_LOGGER &> /dev/null        && unset -f -- __HELLSCRIPTS_LOGGER
-        type __HELLSCRIPTS_ERROR_LOGGER &> /dev/null  && unset -f -- __HELLSCRIPTS_ERROR_LOGGER
+    type __HELLSCRIPTS_LOGGER &> /dev/null        && unset -f -- __HELLSCRIPTS_LOGGER
+    type __HELLSCRIPTS_ERROR_LOGGER &> /dev/null  && unset -f -- __HELLSCRIPTS_ERROR_LOGGER
 
-        function __HELLSCRIPTS_LOGGER {
-            if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
-            then
-                2>&1 echo -e "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS
-            fi
-        }
-
-        function __HELLSCRIPTS_ERROR_LOGGER {
-            if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
-            then
-                >&2 echo -e "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS
-            fi
-        }
-
-        if [[ ! $__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING] ]]
+    function __HELLSCRIPTS_LOGGER {
+        if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
         then
-            __HELLSCRIPTS_SETUP_LOGGER "(Name squatting __HELLSCRIPTS_LOGGER: Phony function)..."
-            __HELLSCRIPTS_SETUP_LOGGER "(Name squatting __HELLSCRIPTS_ERROR_LOGGER: Phony function)..."
-            function __HELLSCRIPTS_LOGGER {}
-            function __HELLSCRIPTS_ERROR_LOGGER {}
+            2>&1 echo -e "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS
         fi
-
-        __HELLSCRIPTS_LOGGER "Injected __HELLSCRIPTS_LOGGER..."
-        __HELLSCRIPTS_LOGGER "Injected __HELLSCRIPTS_ERROR_LOGGER..."
     }
+
+    function __HELLSCRIPTS_ERROR_LOGGER {
+        if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
+        then
+            >&2 echo -e "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS
+        fi
+    }
+
+    if [[ ! $__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING] ]]
+    then
+        __HELLSCRIPTS_SETUP_LOGGER "(Name squatting __HELLSCRIPTS_LOGGER: Phony function)..."
+        __HELLSCRIPTS_SETUP_LOGGER "(Name squatting __HELLSCRIPTS_ERROR_LOGGER: Phony function)..."
+        function __HELLSCRIPTS_LOGGER {}
+        function __HELLSCRIPTS_ERROR_LOGGER {}
+    fi
+
+    __HELLSCRIPTS_LOGGER "Injected __HELLSCRIPTS_LOGGER..."
+    __HELLSCRIPTS_LOGGER "Injected __HELLSCRIPTS_ERROR_LOGGER..."
 
     __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_FETCH_PATHES..."
     function __HELLSCRIPTS_FETCH_PATHES {
@@ -336,7 +334,6 @@ function __HELLSCRIPTS_RUN_INSTALLER {
     else
         __HELLSCRIPTS_SETUP_LOGGER "Injecting a Phony HellScripts logger into your Shell env..."
     fi
-    __HELLSCRIPTS_INJECT_LOGGER
 
     __HELLSCRIPTS_SETUP_APPEND_DEPENDENCY "git" "zsh" "curl" "awk"
     __HELLSCRIPTS_SETUP_LOGGER "Checking if you have imported HellScripts Repo..."
