qsdsqdsq

diff --git a/hell-installer b/hell-installer
--- a/hell-installer
+++ b/hell-installer
@@ -190,31 +190,29 @@ function __HELLSCRIPTS_INJECT_FUNS {
         type __HELLSCRIPTS_LOGGER &> /dev/null        && unset -f -- __HELLSCRIPTS_LOGGER
         type __HELLSCRIPTS_ERROR_LOGGER &> /dev/null  && unset -f -- __HELLSCRIPTS_ERROR_LOGGER
 
-        function __HELLSCRIPTS_LOGGER {
-            if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
-            then
-                2>&1 echo -e "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS
-            fi
-        }
+        if __HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]
+        then
+            function __HELLSCRIPTS_LOGGER {
+                if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
+                then
+                    2>&1 echo -e "[HellScripts] ${@}" | __HELLSCRIPTS_WRITE_LOGS
+                fi
+            }
 
-        __HELLSCRIPTS_LOGGER "Injected __HELLSCRIPTS_LOGGER..."
-        __HELLSCRIPTS_LOGGER "Injecting __HELLSCRIPTS_ERROR_LOGGER..."
-        function __HELLSCRIPTS_ERROR_LOGGER {
-            if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
-            then
-                >&2 echo -e "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS
-            fi
-        }
-    }
-
-    __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_INJECT_PHONY_LOGGER..."
-    function __HELLSCRIPTS_INJECT_PHONY_LOGGER {
-        type __HELLSCRIPTS_LOGGER &> /dev/null        && unset -f -- __HELLSCRIPTS_LOGGER
-        type __HELLSCRIPTS_ERROR_LOGGER &> /dev/null  && unset -f -- __HELLSCRIPTS_ERROR_LOGGER
-        __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_LOGGER (Name squatting: Phony function)..."
-        __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_ERROR_LOGGER (Name squatting: Phony function)..."
-        function __HELLSCRIPTS_LOGGER {}
-        function __HELLSCRIPTS_ERROR_LOGGER {}
+            __HELLSCRIPTS_LOGGER "Injected __HELLSCRIPTS_LOGGER..."
+            __HELLSCRIPTS_LOGGER "Injecting __HELLSCRIPTS_ERROR_LOGGER..."
+            function __HELLSCRIPTS_ERROR_LOGGER {
+                if "$__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]"
+                then
+                    >&2 echo -e "[HellScripts ERROR] ${@}" 2>&1 | __HELLSCRIPTS_WRITE_LOGS
+                fi
+            }
+        else
+            __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_LOGGER (Name squatting: Phony function)..."
+            __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_ERROR_LOGGER (Name squatting: Phony function)..."
+            function __HELLSCRIPTS_LOGGER {}
+            function __HELLSCRIPTS_ERROR_LOGGER {}
+        fi
     }
 
     __HELLSCRIPTS_SETUP_LOGGER "Injecting __HELLSCRIPTS_FETCH_PATHES..."
@@ -334,11 +332,10 @@ function __HELLSCRIPTS_RUN_INSTALLER {
     if $__HELLSCRIPTS_ATTR[ENABLE_HELLSCRIPTS_LOGGING]
     then
         __HELLSCRIPTS_SETUP_LOGGER "Injecting HellScripts logger into your Shell env..."
-        __HELLSCRIPTS_INJECT_LOGGER
     else
         __HELLSCRIPTS_SETUP_LOGGER "Injecting a Phony HellScripts logger into your Shell env..."
-        __HELLSCRIPTS_INJECT_PHONY_LOGGER
     fi
+    __HELLSCRIPTS_INJECT_LOGGER
 
     __HELLSCRIPTS_SETUP_APPEND_DEPENDENCY "git" "zsh" "curl" "awk"
     __HELLSCRIPTS_SETUP_LOGGER "Checking if you have imported HellScripts Repo..."
